language: python

python:
  - "3.7"

jobs:
  include:
    - stage: "Build Lab 2."
      name: "Run tests for Lab 2"
      python: 3.7
      before_install:
        - chmod +x ./lab_*/scripts/travis-build.sh
      install:
        - cd ./lab_2/
        - pipenv install
        - make install
      script: ./scripts/travis-build.sh
    - stage: "Build Lab 3."
      name: "Run Djungo Server and test it accessibility. Fail to run and test"
      python: 3.7
      install:
        - cd ./lab_3/
        - pipenv install
      script: ./scripts/travis-build.sh
    - stage: "Build Lab 4."
      name: "Build Docker images & Home task"
      services:
        - docker
      install:
        - cd ./lab_4/
      script: ./scripts/travis-build.sh
    - stage: "Build Lab 5."
      name: "Build and run Docker images via make"
      services:
        - docker
      install:
        - cd ./lab_5/
        - make app
        - make tests
      script: ./scripts/travis-build.sh
branches:
  only:
    - master